---
title: "p8105_hw5_yw3236"
output: github_document
author: "Yishan Wang"
date: "2018-11-02"
---

# Problem 1

```{r include = FALSE}
library(tidyverse)
library(rvest)
library(httr)
```

```{r}
multmerge = function(mypath){

  filenames = list.files(path = mypath, full.names = TRUE)  #read file names as a list
  data = data_frame(filenames) %>%  #create a dataframe
    mutate(file_contents = purrr::map(filenames, function(x){read.csv(file = x, header = T)})) %>%  #read each file
    unnest()  #unnest each file
  
}
```

This is the second method that using for loop to create filenames column. (`eval=FALSE`)
```{r eval=FALSE}
multmerge = function(mypath){

  filenames = list.files(path = mypath, full.names = TRUE)  #read file names as a list
  datalist = purrr::map(filenames, function(x){read.csv(file = x, header = T)})  #read each csv file and store as a list
  names(datalist) = filenames
  names(datalist) = filenames
  for (i in filenames) {
   datalist[[i]]$filenames = i  #create a new column for file names
  }
  Reduce(function(x, y){rbind(x, y)}, datalist)  #combine all elements of the list

}
```

```{r}
mergeddata = multmerge("./data")
```

```{r}
format_merged_data = mergeddata %>%
  mutate(filenames = gsub("^./data/", " ", filenames)) %>%
  mutate(filenames = gsub(".csv$", " ", filenames)) %>%
  mutate(arm = gsub("([A-Za-z]+).*", "\\1", filenames)) %>%  #have arm column
  mutate(id = gsub("con_", " ", filenames)) %>%
  mutate(id = gsub("exp_", " ", id)) %>%
  mutate(id = as.numeric(id)) %>%  #have numeric id column
  select(-filenames) %>%
  gather(key = week, value = obs, week_1:week_8) %>%
  select(id, arm, week, obs) #tidy dataset
```

```{r}
format_merged_data %>%
  group_by(id) %>%  #group by id
  ggplot() +
  geom_line(aes(x = week, y = obs, group = id, color = id)) +
  facet_grid(~arm) +  #compare two groups: con and exp
  labs(x = "Week", y = "Observations")
```

### Comment

# Problem 2

### Describe Data

```{r}
homicides_data = read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")
```

```{r}
summarised_homicides_data = homicides_data %>%
  mutate(city_state = paste(city, state, sep = ", ")) %>%
  mutate(disposition_index = ifelse(disposition == "Closed without arrest" | disposition == "Open/No arrest", 1, 0)) %>%  #create a index 
  group_by(city) %>%
  summarise(total_homicides = n(), unsolved_homicides = sum(disposition_index)) %>%  #summarize total homicides and unsolved homicides
  mutate(total_homicides = as.double(total_homicides))
```

```{r}
baltimore_unsolved_homicides = summarised_homicides_data %>%
  filter(city == "Baltimore")  #filter Baltimore
  
baltimore_test = prop.test(baltimore_unsolved_homicides$unsolved_homicides, baltimore_unsolved_homicides$total_homicides)  #apply prop.test

broom::tidy(baltimore_test) %>%
  select(estimate, conf.low, conf.high)  #change test result to a dataframe
```

```{r}
prop_test = function(city_data){
  
  city_data %>%
    nest(-city) %>%  #nest first
    mutate(test = purrr::map(data, ~prop.test(.x$unsolved_homicides, .x$total_homicides)),
           tidied = purrr::map(test, broom::tidy)) %>%  #apply test
    unnest(tidied, .drop = TRUE) %>%  #unnest
    select(city, estimate, conf.low, conf.high)
  
}
```

```{r}
multicity_test = prop_test(summarised_homicides_data)
```

```{r}
data.frame(multicity_test) %>%
  ggplot() +
  geom_point(aes(x = reorder(city, estimate), y = estimate)) +  #order cities by the value of estimates
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = rel(1))) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high, estimate), width = 0.2) +  #add error bar
  labs(x = "City", y = "Estimate Proportion of Unsolved Homicides")
```
